last edits
Artris/reason-scheduler pull request #20
Opened 2018-07-11 02:14 UTC by selfeki

## Description

(cherry picked from commit 34a1611b2050c5f16589a0777945cd4e5aebb211)

## Checklist
- [x] added unit tests
- [x] run the examples

2018-07-11 05:28 UTC, alireza-a requested changes

2018-07-11 05:28 UTC, alireza-a commented on src/Scheduler.rei
> -type jobId;
you should keep the `jobId`

2018-07-12 04:50 UTC, alireza-a commented on src/Heap.rei
>  exception RemoveElementNotFound;
you should remove this one as well

2018-07-12 20:00 UTC, selfeki commented on src/Heap.rei
>  exception RemoveElementNotFound;
Simply removing that exception would require changing the implementation inside *Scheduler.re* since it uses the `RemoveElementNotFound` exception:

![image](https://user-images.githubusercontent.com/25670459/42656221-71dc00d2-85d3-11e8-9971-236508a47d32.png)

Would you like the implementation changed as well?

2018-07-12 20:01 UTC, selfeki commented on src/Heap.rei
>  exception RemoveElementNotFound;
Because if I just remove the exception from Heap.re it will fail the tests.

2018-07-12 23:19 UTC, alireza-a commented on src/Heap.rei
>  exception RemoveElementNotFound;
no just remove it from the signature

2018-07-13 01:49 UTC, selfeki commented on src/Heap.rei
>  exception RemoveElementNotFound;
Sorry, I meant removing it from Heap.rei - the signature - will fail the tests.

2018-07-13 01:51 UTC, selfeki commented on src/Heap.rei
>  exception RemoveElementNotFound;
Actually, it won't even compile.

2018-07-13 02:22 UTC, alireza-a commented on src/Heap.rei
>  exception RemoveElementNotFound;
yea, I just tried it myself.
It won't work. I have to update the master as well.

2018-07-13 02:25 UTC, closed without merging